// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtTfbOnKGoAFTWQ7p1rpa8YIKMkabvuDI',
    appId: '1:552768874130:web:906b261852c1288043284b',
    messagingSenderId: '552768874130',
    projectId: 'survey-7e186',
    authDomain: 'survey-7e186.firebaseapp.com',
    storageBucket: 'survey-7e186.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv82ETHjyP9Z0pgnbVREFrhTTGK6I-ZQY',
    appId: '1:552768874130:android:4ead92c2b2f45adf43284b',
    messagingSenderId: '552768874130',
    projectId: 'survey-7e186',
    storageBucket: 'survey-7e186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnUHTH9musTvVAAz5udZNz3SihGREAND0',
    appId: '1:552768874130:ios:cddc4ff31795491b43284b',
    messagingSenderId: '552768874130',
    projectId: 'survey-7e186',
    storageBucket: 'survey-7e186.appspot.com',
    iosClientId: '552768874130-55q5g3q16otohiu619q395ji9chjgem1.apps.googleusercontent.com',
    iosBundleId: 'com.example.survey',
  );
}
